CREATE TABLE Product (
  id INT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  desc TEXT,
  SKU VARCHAR(255) NOT NULL,
  category_id INT,
  inventory_id INT,
  price DECIMAL(10,2) NOT NULL,
  discount_id INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES Product_Category(id),
  FOREIGN KEY (inventory_id) REFERENCES Inventory(id)
);
CREATE TABLE Product_Category (
  id INT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  desc TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);
CREATE TABLE Inventory (
  id INT PRIMARY KEY,
  quantity INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);
CREATE TABLE Discount (
  id INT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  desc TEXT,
  discount_percent DECIMAL(5,2) NOT NULL,
  active BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);
